// This file was generated by json2swift. https://github.com/pyckamil/json2swift

import Foundation
import Unbox

public struct Response: Equatable {
    public let response: [Response]
    public init(response: [Response]) {
        self.response = response
    }
}

extension Response: Unboxable {
    public init(unboxer: Unboxer) throws {
        self.response = try unboxer.unbox(key: "Response")
    }
}

public func == (lhs: Response, rhs: Response) -> Bool {
    return
        lhs.response == rhs.response
}

extension Response: Serializable {
    func serialize() -> Any {
        var serializationDictionary: [AnyHashable: Any] = [:]
        serializationDictionary["Response"] = response.serialize()
        return serializationDictionary
    }
}
